# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1V5CYGzGILepR_65K-VPubDj75nqjlKbU
"""

def search(list,element):
  for i in range(len(list)):
    if list[i] == element:
      return True
  return False
s = ['1','3','5','7','34','56','21']
element='6'
if search(s,element):
  print("The element is found")
else:
  print("The element is not found")